/**
 * AXAM Demo — Exam Module
 * Shows the full setup form. When user clicks Generate, shows the demo modal.
 */
const ExamModule = (() => {
  let state = 'setup';

  function init() {
    if (state === 'setup') renderSetup();
  }

  function prefill(topic, videoId) {
    state = 'setup';
    renderSetup();
    setTimeout(() => {
      const topicInput = document.getElementById('exam-topic');
      const vidInput = document.getElementById('exam-video-id');
      if (topicInput) topicInput.value = topic || '';
      if (vidInput) vidInput.value = videoId || '';
    }, 50);
  }

  function renderSetup() {
    state = 'setup';
    const container = document.getElementById('exam-content');
    container.innerHTML = `
      <div class="exam-setup">
        <div style="text-align:center; margin-bottom:32px;">
          <div style="font-size:48px; margin-bottom:12px;">\uD83D\uDCDD</div>
          <h2 style="font-size:20px; font-weight:700;">Generate Practice Exam</h2>
          <p class="text-muted" style="margin-top:6px;">
            Enter a topic and we'll create questions from MIT lecture content
          </p>
        </div>

        <div class="form-group">
          <label class="form-label">Topic or Subject *</label>
          <input type="text" class="input" id="exam-topic"
                 placeholder="e.g., Quantum mechanics, Supply and demand, DNA replication\u2026">
        </div>

        <div class="form-group">
          <label class="form-label">Number of Questions</label>
          <select class="input" id="exam-count">
            <option value="3">3 \u2014 Quick Quiz</option>
            <option value="5" selected>5 \u2014 Standard</option>
            <option value="10">10 \u2014 Comprehensive</option>
            <option value="15">15 \u2014 Full Exam</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-label">Question Type</label>
          <select class="input" id="exam-type">
            <option value="multiple_choice">Multiple Choice</option>
            <option value="short_answer">Short Answer</option>
          </select>
        </div>

        <input type="hidden" id="exam-video-id" value="">

        <button class="btn btn-primary btn-lg w-full" onclick="ExamModule.generate()" id="exam-generate-btn">
          \uD83C\uDFAF Generate Questions
        </button>

        <p class="text-muted text-sm text-center mt-4">
          Questions are generated by AI from real MIT lecture content.
        </p>
      </div>
    `;
  }

  function generate() {
    const topic = document.getElementById('exam-topic').value.trim();
    if (!topic) {
      AXAM.toast('Please enter a topic', 'warning');
      return;
    }

    // Show loading briefly, then demo modal
    const container = document.getElementById('exam-content');
    const count = document.getElementById('exam-count').value;
    container.innerHTML = `
      <div class="empty-state" style="min-height:300px;">
        <div class="spinner" style="width:40px;height:40px;border-width:4px;"></div>
        <div class="mt-4" style="font-size:16px;color:var(--text-primary);">Generating ${AXAM.esc(count)} questions\u2026</div>
        <div class="text-muted text-sm mt-2">
          Topic: "${AXAM.esc(topic)}"<br>
          Searching MIT lectures and creating questions\u2026
        </div>
      </div>
    `;

    setTimeout(() => {
      renderSetup();
      // Re-fill the topic so user doesn't lose it
      setTimeout(() => {
        const topicInput = document.getElementById('exam-topic');
        if (topicInput) topicInput.value = topic;
      }, 50);

      AXAM.showDemoModal('Exam Generation', '\uD83D\uDCDD');
    }, 1500);
  }

  return {
    init,
    prefill,
    generate,
    renderSetup,
  };
})();
